# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82c387c3f0179cbab494298e178b9d8f79dea8c29fcbb6a1319cb18e6ac9ae410c5d1db5d6acef7b111f1032a11466613972bb8b9dfafc905ca1877e7bc9ac2a

test:
  secret_key_base: 0a7f7f8c624a1547b51ebf58d6f117a5f94d39bcbf957bea704e0539d9d0273339bfe0d835603158d35137d22638f658196a27a9172afada0b1d346e4abd6fb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
